services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sertifikat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Yoqub0522
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

#  bot:
#    build:
#      context: .
#      dockerfile: Dockerfile.bot
#    command: >
#      sh -c "python manage.py wait_for_db &&
#             python bot.py"
#    volumes:
#      - .:/app
#      - media_data:/app/media
#    env_file:
#      - .env
#    depends_on:
#      - django

volumes:
  postgres_data:
  media_data:
