# Generated by Django 5.2 on 2025-05-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.DateField(blank=True, null=True, verbose_name='published_year'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='total'),
        ),
    ]
